name: CI/CD Projeto Fullstack Teste

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python for Backend
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache-dependency-path: 'backend/requirements.txt'

      - name: Install Backend Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
        working-directory: ./backend

      - name: Run Backend Tests
        run: python -m pytest tests/
        working-directory: ./backend

      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install Frontend Dependencies
        run: npm install
        working-directory: ./frontend

      - name: Run Frontend Tests
        run: npm test
        working-directory: ./frontend

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-backend:${{ github.sha }}
          file: ./backend/Dockerfile

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-frontend:${{ github.sha }}
          file: ./frontend/Dockerfile